// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGtgMGaLkddyUh-gr0FyjKXmC6zN5wck',
    appId: '1:75410933593:web:0abc5188f13db45725ae48',
    messagingSenderId: '75410933593',
    projectId: 'kanban-board-2d91f',
    authDomain: 'kanban-board-2d91f.firebaseapp.com',
    storageBucket: 'kanban-board-2d91f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFyUvmS-SFUcjm_gBJAlAVZcHBMw-jlc',
    appId: '1:75410933593:android:a24995fdbc769ae425ae48',
    messagingSenderId: '75410933593',
    projectId: 'kanban-board-2d91f',
    storageBucket: 'kanban-board-2d91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLqrznFls-kk4pWepdMQSuxwPLCYDcrc',
    appId: '1:75410933593:ios:38de7e7fcfd61d0a25ae48',
    messagingSenderId: '75410933593',
    projectId: 'kanban-board-2d91f',
    storageBucket: 'kanban-board-2d91f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLqrznFls-kk4pWepdMQSuxwPLCYDcrc',
    appId: '1:75410933593:ios:38de7e7fcfd61d0a25ae48',
    messagingSenderId: '75410933593',
    projectId: 'kanban-board-2d91f',
    storageBucket: 'kanban-board-2d91f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );
}